### ISSUE TITLE
Inference errors with uploaded model checkpoints

### ISSUE THREAD

**Issue by braydenrudisill** [MolecularAI/Chemformer#27]
I'm looking to run some predictions using the pretrained models you've uploaded (specifically models/fine-tuned/uspto-mixed/last.ckpt), and I've run into issues where pytorch lightning doesn't detect any hyperparams in the checkpoint model. I realize you've uploaded the hyperparams separately, but I'm not sure how to combine them into the model so that pytorch-lightning can load it correctly. Here is the exact error message I get:
```
>> $ python -m molbart.predict --reactants_path tests/test.csv  --model_path uspto_mixed/last.ckpt --task forward_prediction 

File "/baldig/chemistry/2023_rp/Chemformer/molbart/models/chemformer.py", line 387, in _initialize_from_ckpt
    self.model_path, decode_sampler=self.sampler
File "/home/mcangel/anaconda3/envs/chemformer/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 156, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
File "/home/mcangel/anaconda3/envs/chemformer/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 198, in _load_model_state
    model = cls(**_cls_kwargs)
TypeError: __init__() missing 1 required positional argument: 'vocabulary_size'
```

If you have any ideas please let me know!

**Comment by anniewesterlund** [comment]
Hi,
This is due to some changes from release 1.0 and the updated Chemformer-2.0. Specifically, one hyperparameter was renamed from "vocab_size" to "vocabulary_size". You can either run the old model with the code in [Release-1.0](https://github.com/MolecularAI/Chemformer/releases/tag/1.0), or open the model with
```
checkpoint= torch.load("models/fine-tuned/uspto-mixed/last.ckpt")
```
Change the name of "vocab_size" in the dictionary ```checkpoint["hyper_parameters"]``` to "vocabulary_size" and then save the new checkpoint with torch.save,
