### ISSUE TITLE
os.sched_getaffinity error

### ISSUE THREAD

**Issue by Rojina99** [MolecularAI/Chemformer#31]
while running molbart.predict in macos I got the error i received the error `AttributeError: module 'os' has no attribute 'sched_getaffinity'` in molbart/modules/data/base.py. Similary I received error `AttributeError: module 'os' has no attribute 'sched_getaffinity'  in molbart/models/chemformer.py. Currently I handled the issue with 

 ```
 try:
            self._num_workers = len(os.sched_getaffinity(0))
except AttributeError:
            self._num_workers = os.cpu_count() or 1
```

 ```
try:
            n_cpus = len(os.sched_getaffinity(0))
except AttributeError:
            n_cpus = os.cpu_count() or 1  # Default to 1 if cpu_count() is None
```

I am wondering if this serves the original purpose of sched_getaffinity(0) and is there a better way to handle it in mac ?

**Comment by rssrwn** [comment]
Looks like it could be a Mac-specific issue. The main idea behind using sched_getaffinity() is to get the correct number of CPUs that the user has access to (cpu_count() will not always give the correct number when running the code on a server).

For efficient training/inference it's important to make sure the dataloaders use multiple workers so that the data processing and loading is not the bottleneck. If you're not running on a server cpu_count() should give you the correct answer, otherwise you can always just set num_workers to a small number (I think 4 should be sufficient).

**Comment by Rojina99** [comment]
Thank you very much for the clarification.
