### ISSUE TITLE
Questions on smiles str canonicalization when inference

### ISSUE THREAD

**Issue by puchapu** [MolecularAI/Chemformer#8]
Hi there, thanks for your great work!

I found that in [predict.py](https://github.com/MolecularAI/Chemformer/blob/main/molbart/predict.py#L28) you directly use the input smiles string rather than a canonical one for inference. Is this intended to be that? If so, will two smiles string for the same molecule lead to different predictions?

Best regards!

**Comment by EBjerrum** [comment]
Yes, that is the way. We predict a given SMILES as is, but as the model has been trained with augmentations, the differences in predictions should not be large between different SMILES of the same molecule. If they are, you may have an OOD sample. You can also augment the SMILES and do several predictions and take the mean prediction, which will improve your results a bit.

In essence, a model trained with with augmentation can predict canonical SMILES, while a model only trained on canonical SMILES can't really predict non-canonical forms. The canonical trained model are usually also worse on the prediction metrics. As example, see what happens if you predict canonical vs. augmented smiles in a model trained with or without augmentation in this classic preprint: https://arxiv.org/abs/1703.07076
